<?php
/**
* @file
* Módulo para probar bases de datos
* Este módulo crea dos tablas en el proceso de intalación y se borran al desinstalar.
*/

/**
 * Implements hook_install().
 */
function db_forcontu_install() {
  //Actualizamos el esquema
  $schema['node'] = array();
  db_forcontu_schema_alter($schema);
  //Añadimos el campo new_field a la tabla {node}
  db_add_field('node', 'new_field', array(
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => 1,
                'description' => 'Nuevo campo.')
  );
  //Guardamos un registro en la tabla db_forcontu1
  $record = array(
    'content' => 'Contenido de este campo',
    'status' => 1,
    'author' => 'Manel Arrufat',
  );
  drupal_write_record('db_forcontu1', &$record);
  //Creamos la variable db_forcontu
  variable_set('db_forcontu', 1);
  //comprobamos que se ha creado la variable db_forcontu
  dpm('db_forcontu');
}

/**
 * Implements hook_uninstall().
 */
function db_forcontu_uninstall() {
  /*
   *variable_del('upload_file_types');
   */
  //variable_del('');
}

/**
 * Implements hook_schema().
 */
function db_forcontu_schema() {
  $schema['db_forcontu1'] = array(
    'description' => 'Stores example table 1',
    'fields' => array(
      'sid' => array(
        'description' => 'Campo entero autoincremental para identificar el item',
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'content' => array(
        'description' => 'Campo de texto con el contenido del item',
        'type' => 'varchar',
        'length' => 200,
        'not null' => TRUE,
        'default' => '',
      ),
      'status' => array(
        'description' => 'Status del item',
        'type' => 'int',
        'size' => 'tiny',
      ),
      'author' => array(
        'description' => 'Nombre del autor del item',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'primary key' => array('sid'),
  );
  $schema['db_forcontu2'] = array(
    'description' => 'Stores example table 2',
    'fields' => array(
      'nid' => array(
        'description' => 'Campo entero identificador',
        'type' => 'int',
        'not_null' => TRUE,
        'default' => 0,
      ),
      'cid' => array(
        'description' => 'Campo entero identificador',
        'type' => 'int',
        'not_null' => TRUE,
        'default' => 0,
      ),
      'expiration_date' => array(
        'description' => 'Fecha de vencimiento en formato timestamp',
        'type' => 'int',
        'not_null' => TRUE,
      ),
    ),
    'primary key' => array('nid', 'cid'),
  );
  return $schema;
}

/**
 * Implements hook_schema_alter().
 */
function db_forcontu_schema_alter(&$schema) {
  // Add field to existing schema.
  $schema['node']['fields']['new_field'] = array(
    'type' => 'int',
    'unsigned' => TRUE,
    'not null' => TRUE,
    'default' => 1,
    'description' => 'Nuevo campo.',
  );
}